#!/bin/sh

. /etc/init.d/funcs/colors.sh
. /etc/init.d/funcs/init-funcs

case "$1" in
    start)
        printf "$BBLUE**$BYELLOW Setting up hostname\n$RESET"
        /bin/hostname -F /etc/hostname
        check $? "Set up hostname"
        ;;
    stop)
        ;;
    *)
        echo "$0 init script usage: $0 {start}"
        return 1
esac
return $?
