#!/bin/sh

. /etc/init.d/funcs/init-funcs
. /etc/init.d/funcs/colors.sh

case "$1" in
    start)
        printf "$UYELLOW** Mounting virtual filesystems\n$RESET"
        mount -t tmpfs tmpfs /var/run
        check $? "Mount virtual filesystems"
        echo $! > /var/run/networking.pid
        ;;
    stop)
        printf "$UYELLOW Umounting virtual filesystems\n$RESET"
        umount /var/run
        check $? "Umount virtual filesystems"
        rm /var/run/networking.pid
        ;;
    restart|reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "$0 init script usage: $0 {start|stop|restart|reload}"
        return 1
esac
return $?
